<?php

namespace App\Models;

use App\Http\Controllers\FileController;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Assignment
 *
 * @property int $id
 * @property string $name
 * @property int $user_id
 * @property int $file_id
 * @property string $description
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|Assignment newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Assignment newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Assignment query()
 * @method static \Illuminate\Database\Eloquent\Builder|Assignment whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Assignment whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Assignment whereFileId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Assignment whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Assignment whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Assignment whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Assignment whereUserId($value)
 * @mixin \Eloquent
 * @property-read \App\Models\File|null $file
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Submission[] $submissions
 * @property-read int|null $submissions_count
 * @property-read \App\Models\User $user
 */
class Assignment extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'user_id',
        'file_id',
        'description'
    ];

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function submissions()
    {
        return $this->hasMany('App\Models\Submission');
    }

    public function file()
    {
        return $this->belongsTo('App\Models\File');
    }

    public function delete()
    {
        $this->file()->delete();
        $this->submissions()->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
