<?php

namespace App\Models;

use App\Http\Controllers\FileController;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Submission
 *
 * @property int $id
 * @property int $assignment_id
 * @property int $user_id
 * @property int $file_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|Submission newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Submission newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Submission query()
 * @method static \Illuminate\Database\Eloquent\Builder|Submission whereAssignmentId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Submission whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Submission whereFileId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Submission whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Submission whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Submission whereUserId($value)
 * @mixin \Eloquent
 * @property string|null $note
 * @property-read \App\Models\Assignment $assignment
 * @property-read \App\Models\File|null $file
 * @property-read \App\Models\User $user
 * @method static \Illuminate\Database\Eloquent\Builder|Submission whereNote($value)
 */
class Submission extends Model
{
    use HasFactory;

    protected $fillable = [
        'assignment_id',
        'user_id',
        'file_id',
        'note'
    ];

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function assignment()
    {
        return $this->belongsTo('App\Models\Assignment');
    }

    public function file()
    {
        return $this->belongsTo('App\Models\File');
    }

    public function delete()
    {
        $this->file()->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
