version: '3.3'
services:
  php:
    build: .
    volumes:
      - './app:/var/www/html'
  web:
    build:
      context: docker/nginx
    ports:
      - 8000:80
    volumes:
      - './app:/var/www/html'
      - './docker/nginx/conf.nginx:/etc/nginx/conf.d/default.conf'
      - './.docker/log/nginx:/var/log/nginx'
    depends_on:
      - php
    links:
      - php
    extra_hosts:
      - "host.docker.internal:host-gateway"